#!/bin/sh
set -e
APP_DIR="/usr/share/nginx/html"
CONFIG_FILE="$APP_DIR/config.js"
SUPABASE_URL="${SUPABASE_URL:-}"
SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY:-}"
ZOOM_WEBHOOK_URL="${ZOOM_WEBHOOK_URL:-}"
cat > "$CONFIG_FILE" <<EOF
window.__APP_CONFIG__ = {
  SUPABASE_URL: "${SUPABASE_URL}",
  SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY}",
  ZOOM_WEBHOOK_URL: "${ZOOM_WEBHOOK_URL}"
};
EOF
exec "$@"
